spring:
  application:
    name: recipe-api
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:recipeapidb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Mistral AI Configuration
  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY:H4ahht3cf8HMy8LyijpmyMjmRo6SJ4oM}
      chat:
        enabled: true
        options:
          model: mistral-large-latest
          temperature: 0.7
      embedding:
        enabled: false

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:46c3e48c7dc6bc35eb6f5332254669a9a0a29111e6573d169a0fd38c6820b2cc}
    expiration: 86400000
  url: ${APP_URL:http://localhost:8080}

# Server Configuration
server:
  port: ${PORT:8080}
  max-http-request-header-size: 64KB

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html